[package]
name = "pedal-board"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.3"
num-derive = "0.4.2"
num-traits = "0.2.19"
rustfft = "6.2.0"
serde = { version = "1", features = ["derive", "std"] }
serde_json = "1.0.78"

